name: WeRead Sync to Notion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv notion-client
      - name: Run WeRead sync script
        run: |  # 使用 | 符号表示多行字符串
          python sync_weread_to_notion.py \
            --weread_cookie "${{ secrets.WEREAD_COOKIE }}" \
            --notion_token "${{ secrets.NOTION_TOKEN }}" \
            --notion_database_id "${{ secrets.NOTION_DATABASE_ID }}"
